version: '3.9'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  web:
    build: ./django-api-portfolio
    working_dir: /backend/
    volumes:
      - ./django-api-portfolio:/backend
      - static_volume:/backend/static
      - media_volume:/backend/media
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  portfolio-app:
    build:
      context: ./portfolio-app/
    ports:
     - "3000:3000"
    depends_on:
      - web

  postgres:
    image: postgres:15.2
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  postgres:
  static_volume:
  media_volume:
