version: '3.9'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - letsencrypt:/etc/letsencrypt
      - certbot-etc:/etc/certbot
      - certbot-var-www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - certbot


certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-etc:/etc/certbot
      - certbot-var-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot --webroot-path=/var/www/certbot -d queb.online --email antonioquebcastillo@gmail.com --agree-tos --no-eff-email --force-renewal; sleep 12h & wait $${!}; done;'"

  web:
    build: 
      context: ./django-api-portfolio
    working_dir: /backend/
    volumes:
      - ./django-api-portfolio:/backend
      - static_volume:/backend/static
      - media_volume:/backend/media
    expose:
      - 8000
    depends_on:
      - postgres

  portfolio-app:
    build:
      context: ./portfolio-app/
    depends_on:
      - web
    expose:
      - 3000

  postgres:
    image: postgres:15.2
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

volumes:
  postgres:
  static_volume:
  media_volume:
  letsencrypt:
  certbot-etc:
  certbot-var-www:
