version: '3.9'

services:
  cashconverter:
    build: 
      context: ./cash-converter
    ports:
     - "7001:3000"



  cv:
    build: ./app-pdf-viewer
    working_dir: /cv/
    ports:
      - "7000:7000"


  web:
    build: ./django-api-portfolio
    working_dir: /backend/
    volumes:
      - ./django-api-portfolio:/backend
      - static_volume:/backend/static
      - media_volume:/backend/media
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  portfolio-app:
    build:
      context: ./portfolio-app/
    ports:
     - "3000:3000"
    depends_on:
      - web

  postgres:
    image: postgres:15.2
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - media_volume:/usr/src/app/media/  # Añade esta línea
    ports:
      - "80:80"
    depends_on:
      - portfolio-app
      - web

volumes:
  postgres:
  static_volume:
  media_volume:
